// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListFilesFromDirectory(arg1) {
  return window['go']['filenavigator']['FileNavigatorService']['ListFilesFromDirectory'](arg1);
}

export function SelectDirectory() {
  return window['go']['filenavigator']['FileNavigatorService']['SelectDirectory']();
}

export function Startup(arg1) {
  return window['go']['filenavigator']['FileNavigatorService']['Startup'](arg1);
}
