// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ListFilesFromDirectory(arg1:string):Promise<Array<string>>;

export function SelectDirectory():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
